# Generated by Django 3.0.6 on 2020-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestions',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='surveyquestions',
            unique_together={('survey', 'question_number')},
        ),
    ]
