# Generated by Django 3.0.6 on 2020-05-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200527_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.SurveyQuestions')),
            ],
        ),
    ]
