# Generated by Django 3.0.6 on 2020-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_questionresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponses',
            name='response_by',
            field=models.CharField(default='UNKNOWN', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionresponses',
            unique_together={('question', 'response_by')},
        ),
    ]
